# services/cloudflared/config.yml
tunnel: 76614e39-6ea4-431e-a84c-571235b83321
credentials-file: /etc/cloudflared/76614e39-6ea4-431e-a84c-571235b83321.json

ingress:
  - hostname: app.navifes.com
    service: http://nutfesmap-web:3000
  - hostname: api.navifes.com
    service: http://nutfesmap-api:8080
  # ステージングを使うなら下を有効化して別 compose（stg）で上げる
  # - hostname: stg.navifes.com
  #   service: http://stg-web:3000
  # - hostname: stg-api.navifes.com
  #   service: http://stg-api:8080
  - service: http_status:404
